#ifndef MAIN_H_
#define MAIN_H_

#define BUTTON (GPIOA->IDR & GPIO_IDR_IDR0)

#define LED_BLUE_ON  (GPIOC->BSRR = GPIO_BSRR_BS8)
#define LED_BLUE_OFF (GPIOC->BSRR = GPIO_BSRR_BR8)
#define LED_GREEN_ON  (GPIOC->BSRR = GPIO_BSRR_BS9)
#define LED_GREEN_OFF (GPIOC->BSRR = GPIO_BSRR_BR9)

#define IN1_ON 	(GPIOC->BSRR = GPIO_BSRR_BS3)	
#define IN1_OFF	(GPIOC->BSRR = GPIO_BSRR_BR3)	
#define IN2_ON 	(GPIOC->BSRR = GPIO_BSRR_BS2)	
#define IN2_OFF	(GPIOC->BSRR = GPIO_BSRR_BR2)	
#define IN3_ON 	(GPIOC->BSRR = GPIO_BSRR_BS1)	
#define IN3_OFF	(GPIOC->BSRR = GPIO_BSRR_BR1)	
#define IN4_ON 	(GPIOC->BSRR = GPIO_BSRR_BS0)	
#define IN4_OFF	(GPIOC->BSRR = GPIO_BSRR_BR0)	
#endif
